# Generated by Django 5.1.6 on 2026-06-09 05:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=14, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('request_received', 'Request Received'), ('accepted', 'Accepted'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Item(s) Purchased'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Ready for Pickup'), ('closed', 'Closed')], default='request_received', max_length=24)),
                ('buyer_notes', models.TextField(blank=True)),
                ('custom_fare_currency', models.CharField(blank=True, choices=[('IDR', 'IDR — Indonesian Rupiah'), ('USD', 'USD — US Dollar'), ('SGD', 'SGD — Singapore Dollar'), ('MYR', 'MYR — Malaysian Ringgit'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar'), ('JPY', 'JPY — Japanese Yen'), ('CNY', 'CNY — Chinese Yuan'), ('HKD', 'HKD — Hong Kong Dollar'), ('KRW', 'KRW — South Korean Won'), ('THB', 'THB — Thai Baht')], default='', max_length=3)),
                ('custom_fare_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('custom_fare_proof', models.ImageField(blank=True, null=True, upload_to='custom_fare/')),
                ('rejection_reason', models.TextField(blank=True)),
                ('traveler_cleared', models.BooleanField(default=False)),
                ('buyer_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items/requested/')),
                ('estimated_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('purchase_photo', models.ImageField(blank=True, null=True, upload_to='items/purchased/')),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.buyrequest')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('2.5'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='trips.buyrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (to admin)'), ('outbound', 'Outbound (from admin)')], max_length=10)),
                ('kind', models.CharField(choices=[('deposit', 'Buyer deposit'), ('balance', 'Buyer balance (unpaid amount)'), ('payout', 'Payout to traveler'), ('refund', 'Refund')], max_length=10)),
                ('method', models.CharField(choices=[('manual', 'Manual transfer'), ('gateway', 'Payment gateway')], default='manual', max_length=10)),
                ('currency', models.CharField(choices=[('IDR', 'IDR — Indonesian Rupiah'), ('USD', 'USD — US Dollar'), ('SGD', 'SGD — Singapore Dollar'), ('MYR', 'MYR — Malaysian Ringgit'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar'), ('JPY', 'JPY — Japanese Yen'), ('CNY', 'CNY — Chinese Yuan'), ('HKD', 'HKD — Hong Kong Dollar'), ('KRW', 'KRW — South Korean Won'), ('THB', 'THB — Thai Baht')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified / Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='payments/proof/')),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trips.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('travel_date', models.DateField()),
                ('from_city', models.CharField(max_length=80)),
                ('from_country', models.CharField(max_length=80)),
                ('to_city', models.CharField(max_length=80)),
                ('to_country', models.CharField(max_length=80)),
                ('available_weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipment_currency', models.CharField(choices=[('IDR', 'IDR — Indonesian Rupiah'), ('USD', 'USD — US Dollar'), ('SGD', 'SGD — Singapore Dollar'), ('MYR', 'MYR — Malaysian Ringgit'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar'), ('JPY', 'JPY — Japanese Yen'), ('CNY', 'CNY — Chinese Yuan'), ('HKD', 'HKD — Hong Kong Dollar'), ('KRW', 'KRW — South Korean Won'), ('THB', 'THB — Thai Baht')], default='USD', max_length=3)),
                ('shipment_cost_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Applied on top of the ordered items cost.', max_digits=5)),
                ('payment_term', models.TextField(default='50% deposit of items ordered + 100% of shipment cost. Custom fare at the destination country is paid by the buyer (reimbursable to the traveler with proof of payment).')),
                ('status', models.CharField(choices=[('new', 'New'), ('request_received', 'Request Received'), ('accepted', 'Accepted'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Item(s) Purchased'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Ready for Pickup'), ('closed', 'Closed')], default='new', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['travel_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_requests', to='trips.travelplan'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['status', 'travel_date'], name='trips_trave_status_dc0019_idx'),
        ),
    ]
