# Generated by Django 5.1.6 on 2026-06-09 22:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_buyrequest_cleared_at_alter_buyrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='estimated_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
    ]
