# Generated by Django 5.1.6 on 2026-06-09 22:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_backfill_estimated_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='actual_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
    ]
