# Generated by Django 5.1.6 on 2026-06-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_buyrequest_actual_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='purchase_note',
            field=models.CharField(blank=True, help_text='Note if the item is unavailable, short, or substituted.', max_length=255),
        ),
    ]
