# Generated by Django 5.1.6 on 2026-06-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='refund_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='refund_account_no',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='refund_bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
    ]
