# Generated by Django 5.1.6 on 2026-06-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_buyrequest_refund_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='actual_quantity',
            field=models.PositiveSmallIntegerField(default=0, help_text='Quantity actually purchased.'),
        ),
    ]
