# Generated by Django 5.1.6 on 2026-06-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_backfill_actual_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='payment_term',
            field=models.TextField(default='50% deposit of items ordered including margin + 100% of shipment cost. Custom fare at the destination country is paid by the buyer (reimbursable to the traveler with proof of payment).'),
        ),
    ]
