# Generated by Django 5.1.6 on 2026-06-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_alter_travelplan_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='unit',
            field=models.CharField(blank=True, default='pcs', help_text='Unit of measure, e.g. pcs, box, kg.', max_length=20),
        ),
    ]
