# Generated by Django 5.1.6 on 2026-06-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_requestitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'Ordered'), ('accepted', 'Accepted'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Item(s) Purchased'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Ready for Pickup'), ('clear', 'Clear'), ('closed', 'Closed')], default='request_received', max_length=24),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'Ordered'), ('accepted', 'Accepted'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Item(s) Purchased'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Ready for Pickup'), ('clear', 'Clear'), ('closed', 'Closed')], default='new', max_length=24),
        ),
    ]
