# Generated by Django 5.1.6 on 2026-06-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_alter_buyrequest_status_alter_travelplan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trips.buyrequest',),
        ),
    ]
