# Generated by Django 5.1.6 on 2026-06-11 13:59

from django.db import migrations, models

OLD_TERM = (
    "50% deposit of items ordered including margin + 100% of shipment cost. "
    "Custom fare at the destination country is paid by the buyer "
    "(reimbursable to the traveler with proof of payment)."
)
NEW_TERM = (
    "50% deposit of items ordered including margin + 100% of shipment cost. "
    "Custom duty at the destination city is paid by the buyer. "
    "This payment is reimbursable to the traveler with proof of payment."
)


def update_default_terms(apps, schema_editor):
    """Refresh plans that still carry the old default wording (leave any
    traveler-customised payment terms untouched)."""
    TravelPlan = apps.get_model("trips", "TravelPlan")
    TravelPlan.objects.filter(payment_term=OLD_TERM).update(payment_term=NEW_TERM)


def revert_default_terms(apps, schema_editor):
    TravelPlan = apps.get_model("trips", "TravelPlan")
    TravelPlan.objects.filter(payment_term=NEW_TERM).update(payment_term=OLD_TERM)


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='payment_term',
            field=models.TextField(default='50% deposit of items ordered including margin + 100% of shipment cost. Custom duty at the destination city is paid by the buyer. This payment is reimbursable to the traveler with proof of payment.'),
        ),
        migrations.RunPython(update_default_terms, revert_default_terms),
    ]
