# Generated by Django 5.1.6 on 2026-06-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_alter_travelplan_payment_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='shipment_currency',
            field=models.CharField(choices=[('IDR', 'IDR — Indonesian Rupiah'), ('USD', 'USD — US Dollar'), ('SGD', 'SGD — Singapore Dollar'), ('MYR', 'MYR — Malaysian Ringgit'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar'), ('JPY', 'JPY — Japanese Yen'), ('CNY', 'CNY — Chinese Yuan'), ('HKD', 'HKD — Hong Kong Dollar'), ('KRW', 'KRW — South Korean Won'), ('THB', 'THB — Thai Baht')], default='IDR', max_length=3),
        ),
    ]
