# Generated by Django 5.1.6 on 2026-06-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_alter_travelplan_shipment_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='payment_term',
        ),
    ]
