# Generated by Django 5.1.6 on 2026-06-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_remove_travelplan_payment_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
