# Generated by Django 5.1.6 on 2026-06-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_exchangerate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['sequence', 'code']},
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first.'),
        ),
    ]
