# Generated by Django 5.1.6 on 2026-06-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_exchangerate_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
