# Generated by Django 5.1.6 on 2026-06-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_rename_items_purchased_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('clear', 'Clear'), ('closed', 'Closed')], default='request_received', max_length=24),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('clear', 'Clear'), ('closed', 'Closed')], default='new', max_length=24),
        ),
    ]
