# Generated by Django 5.1.6 on 2026-06-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0023_rename_ready_for_pickup_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='awb_document',
            field=models.FileField(blank=True, null=True, upload_to='awb/'),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='awb_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='reshipment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='reshipment_proofs/'),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('reshipping', 'In Transit'), ('clear', 'Clear'), ('closed', 'Closed')], default='request_received', max_length=24),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('reshipping', 'In Transit'), ('clear', 'Clear'), ('closed', 'Closed')], default='new', max_length=24),
        ),
    ]
