# Generated by Django 5.1.6 on 2026-06-14 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_add_reshipment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='reshipment_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='reshipment_bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='reshipment_bank_account_no',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='reshipment_bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='reshipment_cost_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='reshipment_cost_proof',
            field=models.ImageField(blank=True, null=True, upload_to='reshipment_costs/'),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('reship_requested', 'Reship Requested'), ('reship_cost_sent', 'Reship Cost Sent'), ('reshipping', 'In Transit'), ('clear', 'Clear'), ('closed', 'Closed')], default='request_received', max_length=24),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('reship_requested', 'Reship Requested'), ('reship_cost_sent', 'Reship Cost Sent'), ('reshipping', 'In Transit'), ('clear', 'Clear'), ('closed', 'Closed')], default='new', max_length=24),
        ),
    ]
