# Generated by Django 5.1.6 on 2026-06-15 13:20

import apps.trips.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0025_add_reship_flow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrequest',
            name='custom_fare_proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='custom_fare/'),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='reshipment_cost_proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='reshipment_costs/'),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='reshipment_proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='reshipment_proofs/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='chat/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='payments/proof/'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='items/requested/'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='purchase_photo',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='items/purchased/'),
        ),
    ]
