# Generated by Django 5.1.6 on 2026-06-16 05:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_alter_buyrequest_custom_fare_proof_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='bid_cost_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='bid_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='from_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='from_country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='max_acceptable_date',
            field=models.DateField(blank=True, help_text='Deadline for receiving TravelerOffers, and the drop-off grace-period deadline.', null=True),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='partial_allowed',
            field=models.BooleanField(default=False, help_text='Allow this order to be split across multiple travelers.'),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='settlement_currency',
            field=models.CharField(blank=True, choices=[('IDR', 'IDR — Indonesian Rupiah'), ('USD', 'USD — US Dollar'), ('SGD', 'SGD — Singapore Dollar'), ('MYR', 'MYR — Malaysian Ringgit'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar'), ('JPY', 'JPY — Japanese Yen'), ('CNY', 'CNY — Chinese Yuan'), ('HKD', 'HKD — Hong Kong Dollar'), ('KRW', 'KRW — South Korean Won'), ('THB', 'THB — Thai Baht')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='to_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='to_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='to_country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='to_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_requests', to='trips.travelplan'),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('reship_requested', 'Reship Requested'), ('reship_cost_sent', 'Reship Cost Sent'), ('reshipping', 'In Transit'), ('clear', 'Clear'), ('closed', 'Closed'), ('open', 'Awaiting Traveler'), ('responded', 'Responded'), ('taken', 'Taken'), ('package_dropped_off', 'Package Dropped Off'), ('weight_verified', 'Weight Verified'), ('package_received', 'Package Received'), ('no_response', 'No Response'), ('dropoff_missed', 'Dropoff Missed')], default='request_received', max_length=24),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('reship_requested', 'Reship Requested'), ('reship_cost_sent', 'Reship Cost Sent'), ('reshipping', 'In Transit'), ('clear', 'Clear'), ('closed', 'Closed'), ('open', 'Awaiting Traveler'), ('responded', 'Responded'), ('taken', 'Taken'), ('package_dropped_off', 'Package Dropped Off'), ('weight_verified', 'Weight Verified'), ('package_received', 'Package Received'), ('no_response', 'No Response'), ('dropoff_missed', 'Dropoff Missed')], default='new', max_length=24),
        ),
        migrations.CreateModel(
            name='TravelerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_cost_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avail_kg', models.DecimalField(decimal_places=2, help_text="Traveler's declared spare capacity — shown publicly.", max_digits=6)),
                ('drop_off_address', models.TextField(blank=True)),
                ('drop_off_postal_code', models.CharField(blank=True, max_length=20)),
                ('pickup_address', models.TextField(blank=True)),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField(blank=True, null=True)),
                ('from_city', models.CharField(max_length=80)),
                ('from_country', models.CharField(max_length=80)),
                ('to_city', models.CharField(max_length=80)),
                ('to_country', models.CharField(max_length=80)),
                ('offer_status', models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10)),
                ('allocated_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('leg_status', models.CharField(blank=True, choices=[('package_dropped_off', 'Package Dropped Off'), ('weight_verified', 'Weight Verified'), ('package_received', 'Package Received'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Ready for Pickup'), ('clear', 'Clear'), ('closed', 'Closed'), ('dropoff_missed', 'Dropoff Missed')], max_length=24, null=True)),
                ('agreed_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text="Traveler's final measured weight at WEIGHT_VERIFIED — always authoritative.", max_digits=6, null=True)),
                ('fulfillment_method', models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('reship', 'Reship')], max_length=10)),
                ('dropped_off_at', models.DateTimeField(blank=True, null=True)),
                ('weight_verified_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_offers', to='trips.buyrequest')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'offer_status'], name='trips_trave_order_i_2c8012_idx')],
            },
        ),
    ]
