# Generated by Django 5.1.6 on 2026-06-16 06:31

import apps.trips.storage
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0027_buyrequest_bid_cost_per_kg_buyrequest_bid_weight_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('2.5'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='trips.traveleroffer')),
            ],
        ),
        migrations.CreateModel(
            name='LegPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (to admin)'), ('outbound', 'Outbound (from admin)')], max_length=10)),
                ('kind', models.CharField(choices=[('deposit', 'Traveler deposit'), ('balance', 'Weight-delta balance'), ('payout', 'Payout to traveler'), ('refund', 'Refund')], max_length=10)),
                ('method', models.CharField(choices=[('manual', 'Manual transfer'), ('gateway', 'Payment gateway')], default='manual', max_length=10)),
                ('currency', models.CharField(choices=[('IDR', 'IDR — Indonesian Rupiah'), ('USD', 'USD — US Dollar'), ('SGD', 'SGD — Singapore Dollar'), ('MYR', 'MYR — Malaysian Ringgit'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar'), ('JPY', 'JPY — Japanese Yen'), ('CNY', 'CNY — Chinese Yuan'), ('HKD', 'HKD — Hong Kong Dollar'), ('KRW', 'KRW — South Korean Won'), ('THB', 'THB — Thai Baht')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified / Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('proof', models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='leg_payments/proof/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_leg_payments', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trips.legtransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
