# Generated by Django 5.1.6 on 2026-06-16 06:59

import apps.trips.storage
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0028_legtransaction_legpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveleroffer',
            name='awb_document',
            field=models.FileField(blank=True, null=True, upload_to='leg_awb/'),
        ),
        migrations.AddField(
            model_name='traveleroffer',
            name='awb_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='traveleroffer',
            name='cleared_at',
            field=models.DateTimeField(blank=True, help_text='When the buyer marked this leg Clear.', null=True),
        ),
        migrations.AddField(
            model_name='traveleroffer',
            name='reshipment_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traveleroffer',
            name='reshipment_bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='traveleroffer',
            name='reshipment_bank_account_no',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='traveleroffer',
            name='reshipment_bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='traveleroffer',
            name='reshipment_cost_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='traveleroffer',
            name='reshipment_cost_proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='leg_reshipment_costs/'),
        ),
        migrations.AddField(
            model_name='traveleroffer',
            name='reshipment_proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='leg_reshipment_proofs/'),
        ),
        migrations.AlterField(
            model_name='traveleroffer',
            name='leg_status',
            field=models.CharField(blank=True, choices=[('package_dropped_off', 'Package Dropped Off'), ('weight_verified', 'Weight Verified'), ('package_received', 'Package Received'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Ready for Pickup'), ('reship_requested', 'Reship Requested'), ('reship_cost_sent', 'Reship Cost Sent'), ('reshipping', 'In Transit'), ('clear', 'Clear'), ('closed', 'Closed'), ('dropoff_missed', 'Dropoff Missed')], max_length=24, null=True),
        ),
    ]
