# Generated by Django 5.1.6 on 2026-06-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0029_traveleroffer_awb_document_traveleroffer_awb_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveleroffer',
            name='refund_bank_details',
            field=models.TextField(blank=True),
        ),
    ]
