# Generated by Django 5.1.6 on 2026-06-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0030_traveleroffer_refund_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='apply_to_countries',
            field=models.TextField(blank=True, default='', help_text='Comma-separated country names (matching the order form\'s country list, e.g. "United States, Singapore") that should settle in this currency. Buyer-first orders fall back to IDR if no match is found.'),
        ),
    ]
