# Generated by Django 5.1.6 on 2026-06-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0031_exchangerate_apply_to_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='carrier_only',
            field=models.BooleanField(default=False, help_text='Traveler only carries luggage space — not willing to act as a proxy buyer.'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='travel_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
