# Generated by Django 5.1.6 on 2026-06-17 01:19

import apps.trips.storage
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0032_travelplan_carrier_only_travelplan_travel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveleroffer',
            name='custom_fare_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='traveleroffer',
            name='custom_fare_currency',
            field=models.CharField(blank=True, choices=[('IDR', 'IDR — Indonesian Rupiah'), ('USD', 'USD — US Dollar'), ('SGD', 'SGD — Singapore Dollar'), ('MYR', 'MYR — Malaysian Ringgit'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar'), ('JPY', 'JPY — Japanese Yen'), ('CNY', 'CNY — Chinese Yuan'), ('HKD', 'HKD — Hong Kong Dollar'), ('KRW', 'KRW — South Korean Won'), ('THB', 'THB — Thai Baht')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='traveleroffer',
            name='custom_fare_proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='leg_custom_fare/'),
        ),
    ]
