# Generated by Django 5.1.6 on 2026-06-18 06:52

from django.db import migrations, models


def backfill_cargo_only(apps, schema_editor):
    """All existing buyer-first orders (plan=None) are Cargo today (flow 4),
    so mark them cargo_only=True. Plan-first requests inherit from the plan and
    keep cargo_only=False. See PLAN-flow-taxonomy.md §6."""
    BuyRequest = apps.get_model("trips", "BuyRequest")
    BuyRequest.objects.filter(plan__isnull=True).update(cargo_only=True)


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0033_traveleroffer_custom_fare_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='cargo_only',
            field=models.BooleanField(default=False, help_text='Buyer-first only: buyer already has the goods and needs a Carrier to carry them (no proxy purchasing). False = Products Buyer; True = Cargo Buyer.'),
        ),
        migrations.RunPython(backfill_cargo_only, migrations.RunPython.noop),
    ]
