# Generated by Django 5.1.6 on 2026-06-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0034_buyrequest_cargo_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='buy_rate',
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='sell_rate',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='FX Rate'),
        ),
    ]
