# Generated by Django 5.1.6 on 2026-06-20 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0035_remove_exchangerate_buy_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(choices=[('', 'Select a country'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Bangladesh', 'Bangladesh'), ('Belgium', 'Belgium'), ('Brazil', 'Brazil'), ('Brunei', 'Brunei'), ('Cambodia', 'Cambodia'), ('Canada', 'Canada'), ('China', 'China'), ('Denmark', 'Denmark'), ('Egypt', 'Egypt'), ('Finland', 'Finland'), ('France', 'France'), ('Germany', 'Germany'), ('Hong Kong', 'Hong Kong'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Ireland', 'Ireland'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Jordan', 'Jordan'), ('Kuwait', 'Kuwait'), ('Laos', 'Laos'), ('Macau', 'Macau'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mexico', 'Mexico'), ('Myanmar', 'Myanmar'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('New Zealand', 'New Zealand'), ('Norway', 'Norway'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('Saudi Arabia', 'Saudi Arabia'), ('Singapore', 'Singapore'), ('South Korea', 'South Korea'), ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Taiwan', 'Taiwan'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('United Arab Emirates', 'United Arab Emirates'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Vietnam', 'Vietnam')], max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_buyer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proxy Buyer',
                'verbose_name_plural': 'Proxy Buyers',
                'ordering': ['sequence', 'country', 'name'],
            },
        ),
    ]
