# Generated by Django 5.1.6 on 2026-06-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0036_proxybuyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxybuyer',
            name='margin_range',
            field=models.CharField(blank=True, help_text='Indicative margin shown publicly, e.g. "15-25%". Free text — the actual margin is set per order on the proxy\'s estimate.', max_length=20),
        ),
    ]
