# Generated by Django 5.1.6 on 2026-06-20 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0037_proxybuyer_margin_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='proxy_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trips.proxybuyer'),
        ),
    ]
