# Generated by Django 5.1.6 on 2026-06-20 16:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0038_buyrequest_proxy_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='proxy_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Proxy buyer's margin % on the products (buyer-first Products only).", max_digits=5),
        ),
    ]
