# Generated by Django 5.1.6 on 2026-06-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0039_buyrequest_proxy_margin_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='proxy_first_disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='proxy_second_disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
