# Generated by Django 5.1.6 on 2026-06-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0040_buyrequest_proxy_first_disbursed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='traveler_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
