# Generated by Django 5.1.6 on 2026-06-21 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0041_buyrequest_traveler_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLegAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leg_allocations', to='trips.requestitem')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_allocations', to='trips.traveleroffer')),
            ],
            options={
                'unique_together': {('item', 'leg')},
            },
        ),
    ]
