# Generated by Django 5.1.6 on 2026-06-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0042_itemlegallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveleroffer',
            name='payout_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
