# Generated by Django 5.1.6 on 2026-06-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0043_traveleroffer_payout_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxybuyer',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
