# Generated by Django 5.1.6 on 2026-06-22 06:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0044_proxybuyer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='origin_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_plan', to='trips.traveleroffer'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='prebooked_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Capacity already taken by the proxy cargo this plan was spawned from.', max_digits=6),
        ),
    ]
