# Generated by Django 5.1.6 on 2026-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0045_travelplan_origin_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='pickup_selected',
            field=models.BooleanField(default=False),
        ),
    ]
