# Generated by Django 5.1.6 on 2026-06-22 14:29

import apps.trips.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0046_buyrequest_pickup_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='proxy_first_disbursement_proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='disbursement_proofs/'),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='proxy_second_disbursement_proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='disbursement_proofs/'),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='traveler_payout_proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='disbursement_proofs/'),
        ),
    ]
