# Generated by Django 5.1.6 on 2026-06-22 15:18

import apps.trips.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0047_buyrequest_proxy_first_disbursement_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='proxy_disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='proxy_disbursement_proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='disbursement_proofs/'),
        ),
    ]
