# Generated by Django 5.1.6 on 2026-06-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0048_buyrequest_proxy_disbursed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='origin_offer',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='prebooked_weight_kg',
        ),
    ]
