# Generated by Django 5.1.6 on 2026-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0049_remove_travelplan_origin_offer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveleroffer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Carrier offer', 'verbose_name_plural': 'Carrier offers'},
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='partial_allowed',
            field=models.BooleanField(default=False, help_text='Allow this order to be split across multiple carriers.'),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('reship_requested', 'Reship Requested'), ('reship_cost_sent', 'Reship Cost Sent'), ('reshipping', 'In Transit'), ('clear', 'Clear'), ('closed', 'Closed'), ('open', 'Awaiting Carrier'), ('responded', 'Responded'), ('taken', 'Taken'), ('package_dropped_off', 'Package Dropped Off'), ('weight_verified', 'Weight Verified'), ('package_received', 'Package Received'), ('no_response', 'No Response'), ('dropoff_missed', 'Dropoff Missed')], default='request_received', max_length=24),
        ),
        migrations.AlterField(
            model_name='legpayment',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Carrier deposit'), ('balance', 'Weight-delta balance'), ('payout', 'Payout to carrier'), ('refund', 'Refund')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Buyer deposit'), ('balance', 'Buyer balance (unpaid amount)'), ('payout', 'Payout to carrier'), ('refund', 'Refund')], max_length=10),
        ),
        migrations.AlterField(
            model_name='traveleroffer',
            name='agreed_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Carrier's final measured weight at WEIGHT_VERIFIED — always authoritative.", max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='traveleroffer',
            name='avail_kg',
            field=models.DecimalField(decimal_places=2, help_text="Carrier's declared spare capacity — shown publicly.", max_digits=6),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='carrier_only',
            field=models.BooleanField(default=False, help_text='Carrier only carries luggage space — not willing to act as a proxy buyer.'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('reship_requested', 'Reship Requested'), ('reship_cost_sent', 'Reship Cost Sent'), ('reshipping', 'In Transit'), ('clear', 'Clear'), ('closed', 'Closed'), ('open', 'Awaiting Carrier'), ('responded', 'Responded'), ('taken', 'Taken'), ('package_dropped_off', 'Package Dropped Off'), ('weight_verified', 'Weight Verified'), ('package_received', 'Package Received'), ('no_response', 'No Response'), ('dropoff_missed', 'Dropoff Missed')], default='new', max_length=24),
        ),
    ]
