# Generated by Django 5.1.6 on 2026-06-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0050_alter_traveleroffer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='delivery_preference',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('reship', 'Reship')], default='pickup', max_length=10),
        ),
    ]
