# Generated by Django 5.1.6 on 2026-06-26 17:20

import apps.trips.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0051_buyrequest_delivery_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='box_photo_1',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='package_box/'),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='box_photo_2',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='package_box/'),
        ),
    ]
