# Generated by Django 5.1.6 on 2026-06-27 17:58

import apps.trips.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0052_buyrequest_box_photo_1_buyrequest_box_photo_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='custom_fare_estimate_proof',
            field=models.ImageField(blank=True, null=True, storage=apps.trips.storage.WebPConvertingStorage(), upload_to='custom_fare/'),
        ),
    ]
