# Generated by Django 5.1.6 on 2026-06-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0053_buyrequest_custom_fare_estimate_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audience',
            field=models.CharField(choices=[('all', 'All participants'), ('buyer_proxy', 'Buyer & Proxy'), ('proxy_carrier', 'Proxy & Carrier'), ('carrier_buyer', 'Carrier & Buyer')], default='all', max_length=20),
        ),
    ]
