# Generated by Django 5.1.6 on 2026-06-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0054_message_audience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
