# Generated by Django 5.1.6 on 2026-06-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0055_alter_buyrequest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyrequest',
            name='traveler_cleared',
        ),
    ]
