# Generated by Django 5.1.6 on 2026-06-29 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0057_rename_buyrequest_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('all', 'All participants'), ('buyer_proxy', 'Buyer & Proxy'), ('proxy_carrier', 'Proxy & Carrier'), ('carrier_buyer', 'Carrier & Buyer')], max_length=20)),
                ('last_seen_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reads', to='trips.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'order', 'audience'), name='uniq_chatread_user_order_audience')],
            },
        ),
    ]
