# Generated by Django 5.1.6 on 2026-07-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0058_chatread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('reship_requested', 'Reship Requested'), ('reship_cost_sent', 'Reship Cost Sent'), ('reshipping', 'In Transit'), ('clear', 'Clear'), ('closed', 'Closed'), ('open', 'Awaiting Carrier'), ('estimate_sent', 'Estimate Sent'), ('responded', 'Responded'), ('taken', 'Taken'), ('package_dropped_off', 'Package Dropped Off'), ('weight_verified', 'Weight Verified'), ('package_received', 'Package Received'), ('no_response', 'No Response'), ('dropoff_missed', 'Dropoff Missed')], default='request_received', max_length=24),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('request_received', 'W/f Estimate'), ('accepted', 'Estimate Sent'), ('reopen', 'Reopen'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deposit_paid', 'Deposit Paid'), ('items_purchased', 'Package Ready'), ('package_arrived', 'Package Arrived'), ('ready_for_pickup', 'Paid in Full'), ('reship_requested', 'Reship Requested'), ('reship_cost_sent', 'Reship Cost Sent'), ('reshipping', 'In Transit'), ('clear', 'Clear'), ('closed', 'Closed'), ('open', 'Awaiting Carrier'), ('estimate_sent', 'Estimate Sent'), ('responded', 'Responded'), ('taken', 'Taken'), ('package_dropped_off', 'Package Dropped Off'), ('weight_verified', 'Weight Verified'), ('package_received', 'Package Received'), ('no_response', 'No Response'), ('dropoff_missed', 'Dropoff Missed')], default='new', max_length=24),
        ),
    ]
