# Generated by Django 5.1.6 on 2026-07-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0059_alter_order_status_alter_travelplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preferred_courier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('deposit', "Buyer's First Deposit"), ('balance', "Buyer's Second Deposit"), ('payout', 'Payout to Carrier'), ('refund', 'Refund')], max_length=10),
        ),
    ]
