# Generated by Django 5.1.6 on 2026-07-06 02:50

import apps.trips.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0060_order_preferred_courier_alter_payment_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proxy_buyer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=apps.trips.storage.WebPConvertingStorage(), upload_to='order_photos/')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.order')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
