# Generated by Django 5.1.6 on 2026-07-07 03:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0061_order_proxy_buyer_notes_orderphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_kg', models.DecimalField(decimal_places=2, help_text="Weight held/allocated = the order's Total Estimated Weight at surface time.", max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('source', models.CharField(choices=[('push', 'Auto-surfaced'), ('pull', 'Buyer picked')], default='push', max_length=4)),
                ('offered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Start of the accept window.')),
                ('window_expires_at', models.DateTimeField(help_text='offered_at + SiteSettings.carrier_match_window_hours.')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_match', to='trips.traveleroffer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_matches', to='trips.order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_matches', to='trips.travelplan')),
            ],
            options={
                'verbose_name': 'Carrier match',
                'verbose_name_plural': 'Carrier matches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='trips_carri_order_i_de35d5_idx'), models.Index(fields=['plan', 'status'], name='trips_carri_plan_id_060f6b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('order',), name='uniq_accepted_match_per_order')],
            },
        ),
    ]
