# Generated by Django 5.1.6 on 2026-07-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0062_carriermatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriermatch',
            name='window_expires_at',
            field=models.DateTimeField(help_text='offered_at + SiteSettings.carrier_match_window_minutes.'),
        ),
    ]
