# Generated by Django 5.1.6 on 2026-07-08 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0063_alter_carriermatch_window_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier_first_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_first_orders', to='trips.travelplan'),
        ),
    ]
