# Generated by Django 5.1.6 on 2026-07-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0064_order_carrier_first_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=14, unique=True),
        ),
    ]
