# Generated by Django 5.1.6 on 2026-07-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0065_alter_travelplan_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pending_carrier_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
