# Generated by Django 5.1.6 on 2026-07-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0066_order_carrier_rate_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='customs_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='hs_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
