# Generated by Django 5.1.6 on 2026-07-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0067_requestitem_customs_description_requestitem_hs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='buyer_note',
            field=models.CharField(blank=True, help_text="Buyer's note about this item (cargo orders).", max_length=255),
        ),
    ]
