# Generated by Django 5.1.6 on 2026-07-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0068_requestitem_buyer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveleroffer',
            name='plan',
            field=models.ForeignKey(blank=True, help_text="Travel plan this offer's trip is published as on the Queuing board.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_offers', to='trips.travelplan'),
        ),
    ]
