# Generated by Django 5.1.6 on 2026-07-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0069_traveleroffer_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legpayment',
            name='kind',
            field=models.CharField(choices=[('deposit', "Buyer's First Deposit"), ('balance', 'Weight-delta balance'), ('payout', 'Payout to carrier'), ('refund', 'Refund')], max_length=10),
        ),
    ]
