# Generated by Django 5.1.6 on 2026-07-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0070_alter_legpayment_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_details',
            field=models.TextField(blank=True, help_text="Cargo: receiver's name and address at the destination, as printed on the customs invoice."),
        ),
    ]
