# Generated by Django 5.1.6 on 2026-07-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0071_order_receiver_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legpayment',
            name='kind',
            field=models.CharField(choices=[('deposit', "Buyer's First Deposit"), ('balance', "Buyer's Second Deposit"), ('payout', 'Payout to carrier'), ('refund', 'Refund')], max_length=10),
        ),
    ]
