# Generated by Django 5.1.6 on 2026-07-25 14:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0072_alter_legpayment_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveleroffer',
            name='min_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Minimum weight the buyer is billed for, even if their order is lighter.', max_digits=6),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='min_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Minimum weight the buyer is billed for, even if their order is lighter.', max_digits=6),
        ),
    ]
