# Generated by Django 5.1.6 on 2026-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_details',
            field=models.TextField(blank=True, help_text='For invoice disbursement purpose.'),
        ),
        migrations.AddField(
            model_name='user',
            name='destination_city',
            field=models.CharField(blank=True, help_text="The city you'll actually receive your package in — may differ from the traveler's listed (often airport) city.", max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Pickup address at your destination country, used if you choose local Pickup instead of Reshipment. Also shown on customs invoices. Fill this in now or later, once you decide.'),
        ),
    ]
