# Generated by Django 5.1.6 on 2026-07-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_buyer_destination_city_and_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='buyer_invoice_address',
            field=models.TextField(blank=True, help_text='Reshipment address, if you want the carrier to send your package at your cost — also used as the address data on the customs invoice.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_role_choice',
            field=models.CharField(blank=True, choices=[('traveler', 'Carrier'), ('buyer', 'Buyer')], default='', max_length=10),
        ),
    ]
