from django.urls import path

from . import views

app_name = "trips"

urlpatterns = [
    path("plans/new/", views.plan_create, name="plan_create"),
    path("plans/<int:pk>/edit/", views.plan_edit, name="plan_edit"),
    path("plans/<int:pk>/cancel/", views.plan_cancel, name="plan_cancel"),
    path("orders/new/", views.order_create, name="order_create"),
    path("orders/<int:order_id>/offer/", views.offer_create, name="offer_create"),
    path("orders/<int:order_id>/proxy-estimate/", views.proxy_estimate, name="proxy_estimate"),
    path("orders/<int:order_id>/estimate-accept/", views.proxy_estimate_accept, name="proxy_estimate_accept"),
    path("orders/<int:order_id>/estimate-reject/", views.proxy_estimate_reject, name="proxy_estimate_reject"),
    path("orders/<int:order_id>/proxy-purchase/", views.proxy_purchase, name="proxy_purchase"),
    path("orders/<int:order_id>/accept/", views.order_accept, name="order_accept"),
    path("orders/<int:order_id>/reject/", views.order_reject, name="order_reject"),
    path("orders/<int:order_id>/deposit/", views.order_deposit_pay, name="order_deposit_pay"),
    path("offers/<int:pk>/withdraw/", views.offer_withdraw, name="offer_withdraw"),
    path("offers/<int:pk>/edit/", views.offer_edit, name="offer_edit"),
    path("offers/<int:pk>/select/", views.offer_select, name="offer_select"),
    path("offers/<int:pk>/deposit/", views.leg_deposit_pay, name="leg_deposit_pay"),
    path("offers/<int:pk>/weight-verify/", views.leg_weight_verify, name="leg_weight_verify"),
    path("offers/<int:pk>/arrived/", views.leg_arrived, name="leg_arrived"),
    path("offers/<int:pk>/balance/", views.leg_balance_pay, name="leg_balance_pay"),
    path("offers/<int:pk>/refund-bank/", views.leg_refund_bank, name="leg_refund_bank"),
    path("offers/<int:pk>/fulfillment/", views.leg_choose_fulfillment, name="leg_choose_fulfillment"),
    path("offers/<int:pk>/reship-cost/", views.leg_reship_cost, name="leg_reship_cost"),
    path("offers/<int:pk>/reship-proof/", views.leg_reship_proof, name="leg_reship_proof"),
    path("offers/<int:pk>/reship-ship/", views.leg_reship_ship, name="leg_reship_ship"),
    path("offers/<int:pk>/clear/", views.leg_clear, name="leg_clear"),
    path("plans/<int:pk>/", views.plan_detail, name="plan_detail"),
    path("plans/<int:plan_id>/order/", views.request_create, name="request_create"),
    path("requests/<int:pk>/edit/", views.request_edit, name="request_edit"),
    path("requests/<int:pk>/cancel/", views.request_cancel, name="request_cancel"),
    path("orders/<int:pk>/edit/", views.order_edit, name="order_edit"),
    path("orders/<int:pk>/cancel/", views.order_cancel, name="order_cancel"),
    path("requests/<int:pk>/", views.request_detail, name="request_detail"),
    path("requests/<int:pk>/review/", views.request_review, name="request_review"),
    path("requests/<int:pk>/purchase/", views.request_purchase, name="request_purchase"),
    path("requests/<int:pk>/receive/", views.request_receive, name="request_receive"),
    path("requests/<int:pk>/arrive/", views.request_arrive, name="request_arrive"),
    path("requests/<int:pk>/pay/", views.request_pay, name="request_pay"),
    path("requests/<int:pk>/release-disbursement/", views.release_disbursement, name="release_disbursement"),
    path("requests/<int:pk>/clear/", views.request_clear, name="request_clear"),
    path("requests/<int:pk>/reship-request/", views.request_reship_request, name="request_reship_request"),
    path("requests/<int:pk>/reship-cost/", views.request_reship_cost, name="request_reship_cost"),
    path("requests/<int:pk>/reship/", views.request_reship, name="request_reship"),
    path("requests/<int:pk>/reship-proof/", views.request_reship_proof, name="request_reship_proof"),
    path("requests/<int:pk>/set-courier/", views.request_set_courier, name="request_set_courier"),
    path("requests/<int:pk>/message/", views.request_message, name="request_message"),
    path("requests/<int:pk>/chat-seen/", views.chat_seen, name="chat_seen"),
    path("requests/<int:pk>/refund-bank/", views.request_refund_bank, name="request_refund_bank"),
    path("requests/<int:pk>/customs-invoice/", views.request_customs_invoice, name="request_customs_invoice"),
    path("requests/<int:pk>/invoice/", views.request_invoice, name="request_invoice"),
    path("requests/<int:pk>/packing-list/", views.request_packing_list, name="request_packing_list"),
    path("orders/<int:order_id>/assign-items/", views.order_assign_items, name="order_assign_items"),
    # Carrier-First (Queuing Carrier board + buyer match actions)
    path("carriers/queue/", views.queuing_carrier_board, name="queuing_carrier_board"),
    path("carriers/<int:plan_id>/send-order/", views.send_order_to_carrier, name="send_order_to_carrier"),
    path("matches/<int:pk>/accept/", views.match_accept, name="match_accept"),
    path("matches/<int:pk>/reject/", views.match_reject, name="match_reject"),
    path("fxrate/", views.kurs, name="fxrate"),
]
