# Generated by Django 5.1.6 on 2026-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=240)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promos/')),
                ('url', models.CharField(blank=True, max_length=300)),
                ('cta_label', models.CharField(blank=True, default='Learn more', max_length=40)),
                ('badge', models.CharField(blank=True, help_text="Small label, e.g. 'Sponsored', 'Tip', 'For travelers'.", max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
