# Generated by Django 5.1.6 on 2026-06-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='kind',
            field=models.CharField(choices=[('how-to', 'How To'), ('faq', 'FAQ'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions'), ('generic', 'Generic')], default='generic', max_length=12),
        ),
    ]
