# Generated by Django 5.1.6 on 2026-06-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_sitepage_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_term', models.TextField(default='50% deposit of items ordered including margin + 100% of shipment cost. Custom duty at the destination city is paid by the buyer. This payment is reimbursable to the traveler with proof of payment.', help_text="Shown as the Payment Term on every trip's detail page.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
