# Generated by Django 5.1.6 on 2026-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='payment_term',
            field=models.TextField(default='50% deposit of items ordered including margin + 100% of shipment cost. Custom duty at the destination city is paid by the buyer. This payment is reimbursable to the traveler with proof of payment.', help_text="Shown as the Payment Term on every trip's detail page. HTML allowed, e.g. <ul><li>first point</li><li>second point</li></ul>."),
        ),
    ]
