# Generated by Django 5.1.6 on 2026-06-14 12:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_sitesettings_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='min_remaining_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.99'), help_text='Plans with remaining capacity below this threshold show as Full on the home page and block new orders. Default 0.99 kg.', max_digits=5),
        ),
    ]
