# Generated by Django 5.1.6 on 2026-06-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_add_min_remaining_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_term_carrier',
            field=models.TextField(default='<ul><li>Full payment of shipment cost should be paid at the time Buyer hand over the package to Traveler.</li><li>Custom duty at the destination city is paid Buyer. Traveler will cover the duty payment and should be reimbursed upon showing the proof of payment.</li></ul>', help_text='Shown as the Payment Term on Carrier Only trip detail pages. HTML allowed, e.g. <ul><li>first point</li><li>second point</li></ul>.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='payment_term',
            field=models.TextField(default='50% deposit of items ordered including margin + 100% of shipment cost. Custom duty at the destination city is paid by the buyer. This payment is reimbursable to the traveler with proof of payment.', help_text='Shown as the Payment Term on Proxy Buyer trip detail pages. HTML allowed, e.g. <ul><li>first point</li><li>second point</li></ul>.'),
        ),
    ]
