# Generated by Django 5.1.6 on 2026-06-22 04:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_sitesettings_payment_term_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='platform_fee_min_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text="The 2.5% platform fee is floored to this amount (in IDR). Applied to each traveler payout and to the proxy buyer's final disbursement. Default 50,000.", max_digits=12, verbose_name='Minimum platform fee (IDR)'),
        ),
    ]
