# Generated by Django 5.1.6 on 2026-07-02 20:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_sitesettings_platform_fee_min_idr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='topic',
            field=models.CharField(choices=[('become a proxy buyer', 'Become a Proxy Buyer'), ('inquire about advertising', 'Inquire about Advertising'), ('share feedback', 'Share Feedback'), ('get support', 'Get Support'), ('something other', 'Something Other')], default='become a proxy buyer', max_length=25),
        ),
        migrations.AlterField(
            model_name='promo',
            name='badge',
            field=models.CharField(blank=True, help_text="Small label, e.g. 'Sponsored', 'Tip', 'For carriers'.", max_length=24),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='payment_term',
            field=models.TextField(default='100% of items ordered including margin + 100% of shipment cost, paid upfront. Custom duty at the destination city is paid by the buyer. This payment is reimbursable to the carrier with proof of payment.', help_text='Shown as the Payment Term on Proxy Buyer trip detail pages. HTML allowed, e.g. <ul><li>first point</li><li>second point</li></ul>.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='payment_term_carrier',
            field=models.TextField(default='<ul><li>Full payment of shipment cost should be paid at the time Buyer hand over the package to Carrier.</li><li>Custom duty at the destination city is paid Buyer. Carrier will cover the duty payment and should be reimbursed upon showing the proof of payment.</li></ul>', help_text='Shown as the Payment Term on Carrier Only trip detail pages. HTML allowed, e.g. <ul><li>first point</li><li>second point</li></ul>.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='platform_fee_min_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text="The 2.5% platform fee is floored to this amount (in IDR). Applied to each carrier payout and to the proxy buyer's final disbursement. Default 50,000.", max_digits=12, verbose_name='Minimum platform fee (IDR)'),
        ),
    ]
