# Generated by Django 5.1.6 on 2026-07-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_contactmessage_topic_alter_promo_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='carrier_match_lead_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Carrier-First matching: a queued carrier is only offered to a buyer when its travel date is at least this many days from today — enough runway to purchase and hand the goods over before departure. Default 3.', verbose_name='Carrier-first: minimum lead days'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carrier_match_window_hours',
            field=models.PositiveSmallIntegerField(default=3, help_text="Carrier-First matching: how long a surfaced carrier offer stays live on the buyer's page before it expires and releases its held weight. Default 3 hours.", verbose_name='Carrier-first: accept window (hours)'),
        ),
    ]
