# Generated by Django 5.1.6 on 2026-07-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_sitesettings_carrier_match_lead_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='carrier_match_window_hours',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carrier_match_window_minutes',
            field=models.PositiveSmallIntegerField(default=180, help_text="Carrier-First matching: how long a surfaced carrier offer stays live on the buyer's page before it expires and releases its held weight. Default 180 (3 hours).", verbose_name='Carrier-first: accept window (minutes)'),
        ),
    ]
