# Generated by Django 5.1.6 on 2026-07-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_sitesettings_carrier_match_window_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='topic',
            field=models.CharField(choices=[('become a proxy buyer', 'Become a Proxy Buyer'), ('become a carrier', 'Become a Carrier'), ('inquire about advertising', 'Inquire about Advertising'), ('share feedback', 'Share Feedback'), ('get support', 'Get Support'), ('something other', 'Something Other')], default='become a proxy buyer', max_length=25),
        ),
    ]
