# Generated by Django 5.1.6 on 2026-07-16 16:26

import apps.trips.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_contactmessage_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_term_cargo_buyer',
            field=models.TextField(default=apps.trips.constants.DEFAULT_PAYMENT_TERM_CARGO_BUYER, help_text='Shown as the Payment Term to the Buyer on a Cargo order (no Proxy Buyer involved — the buyer already owns the goods). HTML allowed, e.g. <ul><li>first point</li><li>second point</li></ul>.'),
        ),
    ]
